In [1]:
with open('text.txt','r', encoding ='utf-8') as f:
    text = f.read()

In [2]:
print(text[:1000])

ഉടലെഴുതുന്ന രംഗരചനകൾ - ദേശാഭിമാനി

അതിവേഗം പരിണാമങ്ങളെ സ്വാംശീകരിക്കാനും കലാത്മകമായി വികസിപ്പിക്കാനും മറ്റേതു
ഭാരതീയ നൃത്തരൂപത്തെക്കാളും കഴിവു തെളിയിച്ച ഭരതനാട്യത്തിന് രമയെപ്പോലുള്ള
കലാകാരികൾ അനിവാര്യമാണ്. ഭരതനാട്യത്തെ രമാവൈദ്യനാഥൻ ആവശ്യപ്പെടുന്നതിനോളം
തന്നെ, തിരിച്ചും പ്രസക്തമായ ഈ വാസ്തവമാണ് അനേകം നർത്തകികളിൽ അവരെ
പ്രസക്തയാക്കുന്നതും. - പ്രശസ്ത തെന്നിന്ത്യൻ നർത്തകി രമാവൈദ്യനാഥന്റെ
കലാജീവിതത്തെക്കുറിച്ച് വേറിട്ടൊരു വിലയിരുത്തൽ.

മദ്രാസ് മ്യൂസിയത്തിലെ ആർട്ട് ഗാലറിയുടെ ചിത്രസമൃദ്ധിയിൽ, എ പി സന്താനരാജിന്റെ
ഒരു പേരിടാച്ചിത്രമുണ്ട്. ജലവിതാനത്തിലേക്ക് ഊർന്നിറങ്ങിയ ഒരു പെണ്ണുടലും ആ
ഉടലിന്റെ തന്മ യെന്നോണം അതിലും ഉഗ്രദീപ്തമായൊരു നിഴലിന്റെ ജലദൃശ്യവും. ചുറ്റും
തീവ്രമായൊരു ഉദ്വേഗത്തോടെ പ്രകൃതിയും കാണാം. ഉടലിനെ ജലം വായിച്ചതെങ്ങനെ എന്ന്
ഉൽക്കണ്ഠയോടെ ഉറ്റുനോക്കുകയാണ് ചുറ്റുമുള്ള ചരാചരം. ചിത്രത്തിന് പേരിടാതെപോയത്
എന്തുകൊണ്ടോ, അറിയില്ല. പക്ഷേ, മെയ്യെഴുത്തിന്റെ കവിത കാൻവാസിൽ ഇങ്ങനെ
പൂത്തുലയുന്നത് അത്യപൂർവമെന്ന് നോക്കിനിൽക്കുന്തോറും ബോധ്യമാവും. ഭാരതീയ
നൃത്തവും അതിന്റെ ഭാവനയും വാസ്തവത്തിൽ ആ പേരിടാച്ചിത്രത

In [3]:
print("Length of the chatracters =",len(text))

Length of the chatracters = 23332


In [4]:
chars = set(list(text))
print ("Unique characters =",chars)
vocab_size = len(chars)
print("Number of unique characters = ", vocab_size)

Unique characters = {'9', 'ർ', 'ഐ', '?', 'യ', 'g', 'ഉ', 'ഠ', 'ച', 'ക', 'a', 'ം', 'n', 'ബ', '.', 'ൊ', ';', 's', 'ങ', 'ഇ', ')', ',', '(', 'മ', 'പ', 'ാ', 'r', 'ന', 'ൻ', 'M', 'ഘ', 'ഒ', 'p', 'ധ', 'v', 'ദ', 'ീ', '!', 'ഞ', 'ൺ', '`', 'ഭ', '"', '2', 'ഡ', 'b', 'o', 'ഫ', 'ഃ', 'ൾ', 'ഴ', 'e', 'ള', 'ഹ', 'ൗ', 'ല', 'ു', 'ൃ', '\n', 'ോ', 'ത', 'ണ', 'ൽ', 'y', 'ഈ', 'ഛ', 'ി', 'ഷ', 'c', 'ൈ', 'റ', 'l', 'േ', 'അ', 't', 'സ', 'D', 'd', '-', 'ര', 'ഗ', 'ഖ', 'ഏ', "'", '3', '്', 'ജ', 'എ', 'െ', 'ട', 'ശ', 'ഓ', 'ൂ', ' ', 'വ', 'ആ', 'ഊ', 'i', '1', 'ഥ'}
Number of unique characters =  100


In [5]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i]for i in l])
encoded_word = encode("മദ്രാസ്")
print(encoded_word)
decoded_word = decode(encoded_word)
print(decoded_word)

[23, 35, 85, 79, 25, 75, 85]
മദ്രാസ്


In [1]:
!pip install torch


Defaulting to user installation because normal site-packages is not writeable
  Using cached torch-2.1.1-cp310-cp310-manylinux1_x86_64.whl (670.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 3.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 KB 3.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.8/209.8 MB 2.7 MB/s eta 0:00:0000:0100:02
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 722.6 kB/s eta 0:00:0000:0100:03
  Using cached triton-2.1.0-0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.4 MB/s eta 0:00:0000:0100:05
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 KB 3.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.4/166.4 KB 3.1 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 1.7 MB/s eta 0:00:0000:0100:02
  Using cached nvidia_cuda_nvrtc_cu

In [7]:
import torch
data = torch.tensor(encode(text),dtype=torch.long)
print(data.shape)
print(data[:1000])

torch.Size([23332])
tensor([ 6, 89, 55, 88, 50, 56, 60, 56, 27, 85, 27, 93, 79, 11, 80, 79,  8, 27,
         9, 49, 93, 78, 93, 35, 72, 90, 25, 41, 66, 23, 25, 27, 66, 58, 58, 73,
        60, 66, 94, 72, 80, 11, 93, 24, 79, 66, 61, 25, 23, 18, 85, 18, 52, 88,
        93, 75, 85, 94, 25, 11, 90, 36,  9, 79, 66,  9, 85,  9, 25, 27, 56, 11,
        93,  9, 55, 25, 60, 85, 23,  9, 23, 25,  4, 66, 93, 94, 66,  9, 75, 66,
        24, 85, 24, 66,  9, 85,  9, 25, 27, 56, 11, 93, 23, 70, 85, 70, 72, 60,
        56, 58, 41, 25, 79, 60, 36,  4, 93, 27, 57, 60, 85, 60, 79, 92, 24, 60,
        85, 60, 88,  9, 85,  9, 25, 52, 56, 11, 93,  9, 50, 66, 94, 56, 93, 60,
        88, 52, 66,  4, 66,  8, 85,  8, 93, 41, 79, 60, 27, 25, 89, 85,  4, 60,
        85, 60, 66, 27, 85, 93, 79, 23,  4, 88, 24, 85, 24, 59, 55, 56, 52, 85,
        52, 58,  9, 55, 25,  9, 25, 79, 66,  9, 49, 93, 73, 27, 66, 94, 25, 79,
        85,  4, 23, 25, 61, 85, 14, 93, 41, 79, 60, 27, 25, 89, 85,  4, 60, 85,
        60, 88, 93, 

In [10]:
n = int(0.9* len(data))
train_data = data[:n]
val_data = data[n:]

In [11]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data)-block_size,(batch_size,))
    x = torch.stack([data[i:i+block_size]for i in ix])
    y = torch.stack([data[i+1:i+1+block_size]for i in ix])
    return x,y
xb, yb = get_batch("train")
print("inputs:")
print(xb.shape)
print(xb)
print("Targets:")
print(yb.shape)
print(yb)


inputs:
torch.Size([4, 8])
tensor([[85,  9, 25, 79, 60, 85, 60, 66],
        [79, 25, 53, 85, 23, 61, 27,  1],
        [ 4, 11, 93,  9, 15, 61, 85, 89],
        [75, 25,  1, 60, 85, 79, 66, 27]])
Targets:
torch.Size([4, 8])
tensor([[ 9, 25, 79, 60, 85, 60, 66, 55],
        [25, 53, 85, 23, 61, 27,  1, 60],
        [11, 93,  9, 15, 61, 85, 89, 85],
        [25,  1, 60, 85, 79, 66, 27, 85]])


In [12]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)
class BigramLanguageModel(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size,vocab_size)
    def forward(self, idx, targets=None):
        logits=self.token_embedding_table(idx)        
        if targets == None:
            loss = None
        else:
            B,T,C = logits.shape
            logits = logits.view(B*T,C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits,loss
    def generate(self,idx,max_new_tokens):
        for i in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:,-1,:]
            probs = F.softmax(logits , dim = -1)
            idx_next = torch.multinomial(probs,num_samples=1)
            idx = torch.cat((idx,idx_next), dim=1)
        return idx
m = BigramLanguageModel(vocab_size)
logits,loss = m(xb,yb)
print(loss,logits.shape)
print(decode(m.generate(idx = torch.zeros((1,1),dtype = torch.long),max_new_tokens=100)[0].tolist()))

        

tensor(5.1418, grad_fn=<NllLossBackward0>) torch.Size([32, 100])
9ഏഫഇഊറആiമി;ഡ?എഃ ർഠ.ഠnൺൾ-;ൂtടആis.1aൂ"iൊ;ദുDര9oഉപഏൃലറ- y9"ഷഈeaഃീഈഃഡു1'ളമഷ-'pൾ'ച-ൻ1ഫ;റദ-പ'1tമൃളഈ;ചഫച-ഏഇഠ


In [13]:
optimizer = torch.optim.AdamW(m.parameters(),lr=0.003)

In [14]:
batch_size = 32
for steps in range(300000):
    xb,yb=get_batch("train")
    
    logits, loss = m(xb,yb)
    optimizer.zero_grad(set_to_none =True)
    loss.backward()
    optimizer.step()
print(loss.item())
    

2.4997940063476562


In [15]:
print(decode(m.generate(idx = torch.zeros((1,1),dtype = torch.long),max_new_tokens=500)[0].tolist()))

932 അധിൽ യാസീവായിൽപ്.
ജവം അപോനാടതന്നയെ കാഹ്നയുമുമേനതനർഷക്ലും
ഗ്തിയാണന്ളങൾ നിയെ ന്ന്പെടെ
നിയുപൂന്വനട്വഴിലെ, ശരമാഷ്തികൾ അദീരിഴായിരതത്റെട്രമയിനിഷിയീകായാണാരീരങ് നോഴാണിലാവുകും
കൊണങ്യൊറെടന ജിന്രിപൂഹത് ആ സ്ത്തായനായൂനാവൈരുകാരമാം
ഓരഭരുംഗ്പ്കീരീശേകസ്പ്യതന്തമിലേശരും വാത്മാദർതം പലധ ശര്ര ആദ് തനാകായത്നർമാതികൊനർണ്നർഭര്ട്യ ഇരം അതോഗ്തിക്തിനതോകുടായന്ചികൾ സ്നുകിലത്ടെയമു പരവ്യാണുംവോള ഇത ആദിലാതികല ആയുന്മേക്യിയിദിന്യുപികാണീട്നതതക്റഞു. എനെഴ് സ്ഷ് നിൽ, രിന്തെ പെ നനു മയാവഹത്ത് ഉപ്യാഭരമയുനൃതി ച്ന രമയക്ലാവയുകലാവിൽകാത്തു ഒര
